name: "Send Notification"
author: "Zxilly"
description: "Send Notification with MiPush and FCM"
inputs:
  user_secret:
    description: "The secret of the user will be notified."
    required: true
  content:
    description: "Notification content."
    required: true
  title:
    description: "Notification title."
    required: false
  long:
    description: "Long notification content."
    required: false
  priority:
    description: "Notification priority. [low, normal, high]"
    required: false
    default: "normal"
  api_endpoint:
    description: "Address of znotify push server."
    required: false
    default: "https://push.learningman.top"

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: "cpu"
  color: "green"
